//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int WEB_DELETE_MODULES(Nullable<long> mODULE_ID, ObjectParameter outResult, ObjectParameter outMsg)
        {
            var mODULE_IDParameter = mODULE_ID.HasValue ?
                new ObjectParameter("MODULE_ID", mODULE_ID) :
                new ObjectParameter("MODULE_ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_DELETE_MODULES", mODULE_IDParameter, outResult, outMsg);
        }
    
        public virtual int WEB_DELETE_MODULES_TYPE(string mODULE_TYPE_CODE, ObjectParameter outResult, ObjectParameter outMsg)
        {
            var mODULE_TYPE_CODEParameter = mODULE_TYPE_CODE != null ?
                new ObjectParameter("MODULE_TYPE_CODE", mODULE_TYPE_CODE) :
                new ObjectParameter("MODULE_TYPE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_DELETE_MODULES_TYPE", mODULE_TYPE_CODEParameter, outResult, outMsg);
        }
    
        public virtual int WEB_DELETE_MODULES_TYPE_DETAIL(Nullable<long> iD, ObjectParameter outResult, ObjectParameter outMsg)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_DELETE_MODULES_TYPE_DETAIL", iDParameter, outResult, outMsg);
        }
    
        public virtual ObjectResult<WEB_GET_DETAIL_MODULE_Result> WEB_GET_DETAIL_MODULE(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GET_DETAIL_MODULE_Result>("WEB_GET_DETAIL_MODULE", iDParameter);
        }
    
        public virtual ObjectResult<WEB_GET_LIST_MODULE_Result> WEB_GET_LIST_MODULE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GET_LIST_MODULE_Result>("WEB_GET_LIST_MODULE");
        }
    
        public virtual ObjectResult<WEB_GET_LIST_MODULUES_TYPE_Result> WEB_GET_LIST_MODULUES_TYPE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GET_LIST_MODULUES_TYPE_Result>("WEB_GET_LIST_MODULUES_TYPE");
        }
    
        public virtual ObjectResult<WEB_GET_LIST_MODULUES_TYPE_DETAIL_Result> WEB_GET_LIST_MODULUES_TYPE_DETAIL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GET_LIST_MODULUES_TYPE_DETAIL_Result>("WEB_GET_LIST_MODULUES_TYPE_DETAIL");
        }
    
        public virtual ObjectResult<WEB_GET_LIST_MODULUES_TYPE_DETAIL_BY_TYPE_Result> WEB_GET_LIST_MODULUES_TYPE_DETAIL_BY_TYPE(string mODULE_TYPE_CODE)
        {
            var mODULE_TYPE_CODEParameter = mODULE_TYPE_CODE != null ?
                new ObjectParameter("MODULE_TYPE_CODE", mODULE_TYPE_CODE) :
                new ObjectParameter("MODULE_TYPE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GET_LIST_MODULUES_TYPE_DETAIL_BY_TYPE_Result>("WEB_GET_LIST_MODULUES_TYPE_DETAIL_BY_TYPE", mODULE_TYPE_CODEParameter);
        }
    }
}
